### ISSUE TITLE
recurring weekday-based scheduling

### ISSUE THREAD

**Issue by bw352** [ksalzke/scheduling-omnifocus-plugin#3] opened 2022-04-10 13:18 UTC
What I did: tagged a weekly Sunday deferred task with "Sundays"

What I expected: Today being Sunday, after running the 'update schedule' plug-in, I expected the task to be marked as 'Today'. The defer date of the task is not after the specified day. 

What happened: No change. The tag reminded 'Sundays'

Thanks!

**Comment by ksalzke** [comment] 2022-04-13 11:02
Hi @bw352!

Is it possible that you tagged the task with "Sundays" after the 'Update Schedule' action had already been run for the day, prior to running 'Update Schedule' again?

The plug-in does keep track of whether the plug-in has already been run, and only marks weekly tasks as 'today' on the first run. This is because they don't otherwise have a date specified so is intended to avoid a situation like: a task is tagged with 'Sundays' and marked as 'today' when the action is first run. Then the user decides not to do the task today, so removes the tag/flag; but the action is subsequently run again and so it is re-added.

Happy to consider other approaches or arguments for different behaviour as I'm not 100% convinced this is the best approach, but it is currently expected behaviour if that is indeed the sequence of actions you took.

**Closed as completed** 2022-11-18 23:14 UTC
